stages:
  - build
  - release

variables:
  APP_NAME: "$CI_PROJECT_NAME"
  
win32:build:
  variables:
    ARCH: "x64"
    PLATFORM: "win32"
  image: electronuserland/builder:wine-mono
  stage: build
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install dpkg -y
    - apt-get install fakeroot -y
    - rm -rf /root/.wine
    - winecfg
  script:
    - npm install --save-dev electron
    - npm install --save-dev @electron-forge/cli
    - npx electron-forge import
    - npx electron-forge package --arch=$ARCH --platform=$PLATFORM
  after_script:
    - echo "BUILD_WIN32_JOB_URL=$CI_JOB_URL" >> win32_job.env
    - echo "BUILD_WIN32_NAME=$APP_NAME-$ARCH-$PLATFORM-$CI_COMMIT_TAG" >> win32_job.env
  artifacts:
    name: "$APP_NAME-$ARCH-$PLATFORM-$CI_COMMIT_TAG"
    expire_in: never
    paths:
      - ./out/*
    reports:
      dotenv: win32_job.env

linux:build:
  variables:
    ARCH: "x64"
    PLATFORM: "win32"
  image: electronuserland/builder
  stage: build
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  before_script:
    - apt-get update
    - apt-get upgrade -y
  script:
    - npm install --save-dev electron
    - npm install --save-dev @electron-forge/cli
    - npx electron-forge import
    - npx electron-forge package
  after_script:
    - echo "BUILD_LINUX_JOB_URL=$CI_JOB_URL" >> linux_job.env
    - echo "BUILD_LINUX_NAME=$APP_NAME-$ARCH-$PLATFORM-$CI_COMMIT_TAG" >> linux_job.env
  artifacts:
    name: "eda-spectrometer-x64-linux-$CI_COMMIT_TAG"
    expire_in: never
    paths:
      - ./out/*
    reports:
      dotenv: linux_job.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - win32:build
    - linux:build
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "Create release for tag $CI_COMMIT_TAG"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: "$BUILD_WIN32_NAME"
          url: "$BUILD_WIN32_JOB_URL/artifacts/download"
        - name: "$BUILD_LINUX_NAME"
          url: "$BUILD_LINUX_JOB_URL/artifacts/download"